global:
  scrape_interval: 15s
  external_labels:
    monitor: 'user_metrics'

scrape_configs:
  - job_name: 'neofs-node-user'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']
    relabel_configs:
      - target_label: 'instance'
        replacement: "%{NEOFS_NODE_ADDRESS}"
